"""empty message

Revision ID: 10764861cb17
Revises: 
Create Date: 2020-04-11 14:32:46.403765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10764861cb17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
