"""empty message

Revision ID: 733a3de9d2c1
Revises: e7e35e4b7ad9
Create Date: 2020-04-12 15:58:53.610936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733a3de9d2c1'
down_revision = 'e7e35e4b7ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recruits', 'user', ['id_number'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruits', type_='foreignkey')
    # ### end Alembic commands ###
