"""empty message

Revision ID: 97a59bd67f64
Revises: cd934a00d177
Create Date: 2020-04-11 15:59:02.041384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a59bd67f64'
down_revision = 'cd934a00d177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('chatname', sa.VARCHAR(length=15), nullable=True),
    sa.Column('github_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('id_number', sa.NUMERIC(precision=15), nullable=True),
    sa.Column('personal_email', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('recruits')
    # ### end Alembic commands ###
