"""empty message

Revision ID: cd934a00d177
Revises: 10764861cb17
Create Date: 2020-04-11 14:41:10.502765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd934a00d177'
down_revision = '10764861cb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('personal_email', sa.VARCHAR(length=20), nullable=True))
    op.create_unique_constraint(None, 'recruits', ['personal_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruits', type_='unique')
    op.drop_column('recruits', 'personal_email')
    # ### end Alembic commands ###
