"""empty message

Revision ID: e7e35e4b7ad9
Revises: f6ccc905fc4b
Create Date: 2020-04-12 15:14:12.867040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e35e4b7ad9'
down_revision = 'f6ccc905fc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruits', sa.Column('cohort', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruits', 'cohort')
    # ### end Alembic commands ###
